// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _wescore_lcm_msgs_JideTechCam_h
#define _wescore_lcm_msgs_JideTechCam_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_ZOOM_IN 0
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_ZOOM_OUT 1
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_FOCUS_NEAR 2
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_FOCUS_FAR 3
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_SHUTTER_EXPAND 4
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_SHUTTER_SHRINK 5
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_MOVE_UP 6
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_MOVE_DOWN 7
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_MOVE_LEFT 8
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_MOVE_RIGHT 9
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_MOVE_UP_LEFT 10
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_MOVE_UP_RIGHT 11
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_MOVE_DOWN_LEFT 12
#define WESCORE_LCM_MSGS_JIDETECHCAM_CMD_MOVE_DOWN_RIGHT 13

typedef struct _wescore_lcm_msgs_JideTechCam wescore_lcm_msgs_JideTechCam;
struct _wescore_lcm_msgs_JideTechCam
{
    int32_t    ptz_cmd;
    int32_t    param1;
    int32_t    param2;
};

/**
 * Create a deep copy of a wescore_lcm_msgs_JideTechCam.
 * When no longer needed, destroy it with wescore_lcm_msgs_JideTechCam_destroy()
 */
wescore_lcm_msgs_JideTechCam* wescore_lcm_msgs_JideTechCam_copy(const wescore_lcm_msgs_JideTechCam* to_copy);

/**
 * Destroy an instance of wescore_lcm_msgs_JideTechCam created by wescore_lcm_msgs_JideTechCam_copy()
 */
void wescore_lcm_msgs_JideTechCam_destroy(wescore_lcm_msgs_JideTechCam* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _wescore_lcm_msgs_JideTechCam_subscription_t wescore_lcm_msgs_JideTechCam_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * wescore_lcm_msgs_JideTechCam is received.
 */
typedef void(*wescore_lcm_msgs_JideTechCam_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const wescore_lcm_msgs_JideTechCam *msg, void *userdata);

/**
 * Publish a message of type wescore_lcm_msgs_JideTechCam using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int wescore_lcm_msgs_JideTechCam_publish(lcm_t *lcm, const char *channel, const wescore_lcm_msgs_JideTechCam *msg);

/**
 * Subscribe to messages of type wescore_lcm_msgs_JideTechCam using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
wescore_lcm_msgs_JideTechCam_subscription_t* wescore_lcm_msgs_JideTechCam_subscribe(
    lcm_t *lcm, const char *channel, wescore_lcm_msgs_JideTechCam_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by wescore_lcm_msgs_JideTechCam_subscribe()
 */
int wescore_lcm_msgs_JideTechCam_unsubscribe(lcm_t *lcm, wescore_lcm_msgs_JideTechCam_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int wescore_lcm_msgs_JideTechCam_subscription_set_queue_capacity(
    wescore_lcm_msgs_JideTechCam_subscription_t* subs, int num_messages);

/**
 * Encode a message of type wescore_lcm_msgs_JideTechCam into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to wescore_lcm_msgs_JideTechCam_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int wescore_lcm_msgs_JideTechCam_encode(void *buf, int offset, int maxlen, const wescore_lcm_msgs_JideTechCam *p);

/**
 * Decode a message of type wescore_lcm_msgs_JideTechCam from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with wescore_lcm_msgs_JideTechCam_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int wescore_lcm_msgs_JideTechCam_decode(const void *buf, int offset, int maxlen, wescore_lcm_msgs_JideTechCam *msg);

/**
 * Release resources allocated by wescore_lcm_msgs_JideTechCam_decode()
 * @return 0
 */
int wescore_lcm_msgs_JideTechCam_decode_cleanup(wescore_lcm_msgs_JideTechCam *p);

/**
 * Check how many bytes are required to encode a message of type wescore_lcm_msgs_JideTechCam
 */
int wescore_lcm_msgs_JideTechCam_encoded_size(const wescore_lcm_msgs_JideTechCam *p);

// LCM support functions. Users should not call these
int64_t __wescore_lcm_msgs_JideTechCam_get_hash(void);
uint64_t __wescore_lcm_msgs_JideTechCam_hash_recursive(const __lcm_hash_ptr *p);
int __wescore_lcm_msgs_JideTechCam_encode_array(
    void *buf, int offset, int maxlen, const wescore_lcm_msgs_JideTechCam *p, int elements);
int __wescore_lcm_msgs_JideTechCam_decode_array(
    const void *buf, int offset, int maxlen, wescore_lcm_msgs_JideTechCam *p, int elements);
int __wescore_lcm_msgs_JideTechCam_decode_array_cleanup(wescore_lcm_msgs_JideTechCam *p, int elements);
int __wescore_lcm_msgs_JideTechCam_encoded_array_size(const wescore_lcm_msgs_JideTechCam *p, int elements);
int __wescore_lcm_msgs_JideTechCam_clone_array(const wescore_lcm_msgs_JideTechCam *p, wescore_lcm_msgs_JideTechCam *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
